### ISSUE TITLE
Написать предварительное описание предметной области и требований к системе

### ISSUE THREAD

**Issue by 5Blank1** [5Blank1/TZ_BD#3]

**Comment by 5Blank1** [comment]
**Описание предметной области**

В данном приложении существуют товары , склад с товарами, корзина , заказы .

-У склада есть список товаров, кол-во определенного товара, дата пополнения склада.
-Каждый товар содержит обложку, название , свою категорию, свою стоимость, кол-во на складе;
-Корзина  содержит заказ, стоимость заказа;
-Заказ содержит список товаров , кол-во товаров.

Описание и функционал со стороны администратора:

Администратор имеет доступ ко всем данным системы, а также может с легкостью добавлять, изменять, удалять их.

Описание и функционал со стороны пользователя:

-Просмотр товаров на сайте;
-Добавление товаров в корзину;
-Оформление заказа;
-Просмотр статуса заказа;
-Возможность заказать товар со склада(при условии ,что товара нет на сайте).

**Comment by wldmr-key** [comment]
> В данном приложении существуют товары , склад с товарами, корзина , заказы 

Сразу мимо - это уже требования к тому, что у тебя в приложении должно существовать
Перед этим стоит рассказать о том, как работате магазин стройматериалов: что является товаром, как и кого покупается, хранится, как и кому продается и т.п. - то есть, ввести термины и понятия. Это и называется описанием предметной области.

> Администратор имеет доступ ко всем данным системы, а также может с легкостью добавлять, изменять, удалять их.

например, "с легкостью" изменить количество заказа или количество товаров на складе?

Описание и требования должны быть настолько подробными, чтобы объяснить все сущности и атрибуты, которые появятся в твоей окнцептуальной схеме

**Comment by 5Blank1** [comment]
Мой магазин стройматериалов является универсальным. В подобных точках ассортимент максимально разнообразен и состоит из множества товарных групп, среди которых: сухие строительные смеси, плитка, отделочные материалы, сантехника, электротехнические товары, напольные покрытия и т.д. 

Ассортимент подобных магазинов может включать следующие группы товаров:
**Строительные материалы:**
общестроительные материалы (кирпич, газобетонные и стеновые блоки и  тд)
**Строительные смеси:**
сухие смеси (цемент, ЦПС, кладочные и монтажные растрворы, клей для плитки и тд)
**Отделочные материалы:**
 двери , подоконники; ПВХ; уплотнители; 
**ЛКМ, пены, герметики:**
грунты (антикоррозионные, жидкое стекло); краски водные (для потолка, интерьерные, моющиеся, фасадные, декоративные штукатурки); эмали ; краски масляные; пигменты и колеровочные краски; растворители и очистители; антисептики.
**Плитка и керамомагнит:**
плитка,декоративные элементы; плитка для облицовки фасадов и цоколей; клеи для плитки; затирки; грунтовки;
**Напольные покрытия:**
ламинат; линолеум; плитка ПВХ; 
**Сантехника:**
ванны; душевые углы, поддоны, мойки; смесители; аксессуары для смесителей; 


Администратор имеет доступ ко всем данным системы, а также может с легкостью добавлять, изменять, удалять их. Но есть и исключение, администратор не может изменять  количество заказов или количество товаров на складе, которые присутствуют по факту.

**Comment by 5Blank1** [comment]
![sxema](https://user-images.githubusercontent.com/106016588/200611475-c57084e1-bc2c-4c83-a04f-ac29d1213e4f.jpg)
Подправил таблички, как вы говорили в тот раз. Уже с опорой на них писал сервер часть.

**Comment by wldmr-key** [comment]
ну, ты понял на консультации, где поправить...

**Comment by 5Blank1** [comment]
Владимир Юрьевич , здравствуйте. Возник такой вопрос. У меня в магазине типы и бренды из бд берутся нормально. Админ тоже может спокойно их добавлять через админ панель. Однако проблема в том , что сами продукты из бд не отрисовываются. Админ может добавить продукт в бд, но он не отрисуется))). Долго ломал голову, ибо я тоже самое делаю с брендами и типами , но при этом все работает) (продукт с id7 добавлен через админ панель и он заносится в мою бд) . Можно ли оставить так?(я еще попытаюсь устранить ошибку , но не уверен что получится) 
![image](https://user-images.githubusercontent.com/106016588/205309251-bd1eda9d-e33d-44d8-8651-e495ca68a6c7.png)

**Comment by wldmr-key** [comment]
что значит "не отрисовывается"? где? при каких обстоятельствах?

**Comment by 5Blank1** [comment]
У меня есть массив, который должен быть пустым(в него попадает информация из бд).
![image](https://user-images.githubusercontent.com/106016588/205492109-5c76c9e4-7de6-48ed-be76-2217aa722305.png)
Однако если он останется пустым, на главной странице ничего не отрисуется. 
![image](https://user-images.githubusercontent.com/106016588/205492179-7c08e5a6-2e86-479f-a7da-5339297e1536.png)
Заполнив массив все отрисуется и при переходе на товар будет информация из бд)
![image](https://user-images.githubusercontent.com/106016588/205492266-b75deed9-8e3e-463c-9308-0cddfc02e3d8.png)
![image](https://user-images.githubusercontent.com/106016588/205492303-117b9de2-4744-4e10-96c6-d0ee89bf7406.png)
Я просто не знаю в чем причина и вот хотел узнать можно ли оставить так)

**Comment by wldmr-key** [comment]
причина, очевидно, в том, что твой массив не связывается (неправильно связывается с БД). Разумеется доделывай в начале то, что понятно, а потом разбирайся с этим (покажи код связывания мне или Сафину ))

**Comment by wldmr-key** [comment]
где твои исходники? Должны уже быть в репозитории

**Comment by 5Blank1** [comment]
Сегодня/на днях подгружу все).Просто пытаюсь закрыть семестр пораньше)

**Comment by 5Blank1** [comment]
Здравствуйте, Владимир Юрьевич. Сделал сегодня рпз по бд. Можете быстренько взглянуть на него , сказать что не так?)(P.S. страницы пока не правильно расставлены , завтра поправлю)) )
[RPZ_po_kursovoy_rabote_po_BD_Hlopkov.docx](https://github.com/5Blank1/TZ_BD/files/10200712/RPZ_po_kursovoy_rabote_po_BD_Hlopkov.docx)

**Comment by wldmr-key** [comment]
описание предметной области - магазин обладает неограниченным складом продуктов?

концептуальная схема - продукты заказа не имеют ничего общего с продуктами магазина? верно? Зачем нужна сущность "Корзина"? Все наименования и атрибуты концептуальной схемы должны быть ранее описаны. У тебя не так.

"Для разработки приложения, обладающего перечисленными функциями, необходимо решить, где и как будет применяться СУБД Postgres" - и где и как ты это решаешь?

логическая схема - не стыкуется с концептуальной, Слово "типа" встречается сильно чаще, чем нужно

"Связь many-to-many продуктов и пользователей" и "Связь many-to-many товаров и корзин" присутствует только в твоем воображении и отсутствует в концептуальной схеме

"Все таблицы были реализованы с помощью ORM-библиотеки Sequelize" - чиво?!!!

"Сами определения моделей будут написаны в следующем разделе." ох

**Comment by wldmr-key** [comment]
Тебе и Королеву следует сделать так, чтобы тексты не выглядели идентично. Время есть

**Comment by 5Blank1** [comment]
Правлю ошибки, на которые вы указали в пз:

6пункт:
![image](https://user-images.githubusercontent.com/106016588/207115506-ff1878c5-7b89-4d8d-81f1-259f40efdb0b.png)


1пункт:
![image](https://user-images.githubusercontent.com/106016588/207114377-a2a1abe0-4c45-4bbf-b278-c9821b9cf858.png)


3пункт:
![image](https://user-images.githubusercontent.com/106016588/207114630-6a522ca5-0b3d-4b1f-8f81-5f40ec4ea07d.png)


7пункт:
![image](https://user-images.githubusercontent.com/106016588/207115229-1d0056c0-3a8a-4be0-9c94-8ceee0f01fa0.png)

**Comment by 5Blank1** [comment]
Исправленная концептуальная схема:
![image](https://user-images.githubusercontent.com/106016588/207131419-2b82eabb-a6bb-4be7-a0bf-074ee6446981.png)

**Comment by wldmr-key** [comment]
в пояснительной записке следует убрать первое лицо "созданном мною", прошедшее и будущее время (за исключением случаев, когда это, действительно, необходимо. И согласовать падежи

наличие товара на складе не интересует концептуальную схему? Или это не про данные? ))

**Comment by 5Blank1** [comment]
на складе вместо количества товара, количество позиций товара?
(Условно,есть склад каких то наименований и эти наименования могут быть или отсутствовать на складе( т . е. булево значение).На основании этого, на сайте будет показываться есть это наименование или нет)

**Comment by wldmr-key** [comment]
видимо я, на ночь глядя, твою сущность склад не заметил. Все верно, там должно быть количество (и не должно быть артикулов), чтобы ограничивать число позиций в заказе

**Comment by 5Blank1** [comment]
логическая схема
![image](https://user-images.githubusercontent.com/106016588/207282037-facff8de-b57d-4d7d-8f3b-842802cf1289.png)

**Comment by wldmr-key** [comment]
внешний ключ у склада, не?

**Comment by 5Blank1** [comment]
ой,забыл))))0
![image](https://user-images.githubusercontent.com/106016588/207292121-299855e5-1ac7-4b79-9745-a818a87b0b43.png)

**Comment by 5Blank1** [comment]
думаю это заключительный вариант рпз по бд) (ну почти заключительный:D )
[RPZ_po_kursovoy_rabote_po_BD_Hlopkov.docx](https://github.com/5Blank1/TZ_BD/files/10217690/RPZ_po_kursovoy_rabote_po_BD_Hlopkov.docx)

**Comment by 5Blank1** [comment]
[RPZ_po_kursovoy_rabote_po_BD_Hlopkov.docx](https://github.com/5Blank1/TZ_BD/files/10217686/RPZ_po_kursovoy_rabote_po_BD_Hlopkov.docx)

**Comment by 5Blank1** [comment]
uml admin для аасоиу
![image](https://user-images.githubusercontent.com/106016588/207325409-a65cf9a4-892b-438a-8f87-3f8b1bb37e95.png)

uml user для аасоиу
![image](https://user-images.githubusercontent.com/106016588/207352213-aea365eb-e494-45c4-9c64-b83ab39809af.png)
(только не понимаю как у пользователя привязатб рейтинг , ибо пользователь ставит рейтинг продукту , а не заказу)
![image](https://user-images.githubusercontent.com/106016588/207355840-35e9f98d-8030-4f42-9d21-d714e5e7877b.png)

**Comment by wldmr-key** [comment]
это очень мило, что ты в один issue лепишь все, в том числе и то, что ко мне никак не относится ))
